### ISSUE TITLE
Override License field for some projects

### ISSUE THREAD

**Issue by maoo** [finos/finos-landscape#131]
In the following link there are 5 projects listed as "Non OpenSource"; the reason is that they are not hosted in GitHub (bur rather in GitLab), so they don't define a `repo_url ` and GitHub API cannot fetch license info (I guess)

https://landscape.finos.org/card-mode?grouping=license&license=not-open-source

@jordinl83 - is there a field we can use in `landscape.yml` to force the license to show for a certain `item` ? This would also greatly help us with licenses that are not even mapped into GitHub (or GitLab) list, like CSLA 1.0 (See https://github.com/finos/standards-project-blueprint ) .

**Comment by jordinl83** [comment]
I think you could set `open_source: true` on an item. Don't think you can manually set which license an item has though

**Comment by AndreyKozlov1984** [comment]
We do not support manually setting a license. If you have a list of explicit licenses for such case - I can support an explicit set of a license.

Usually we use an `open_source: false` to notify that while there is a repo_url - this is still not an open source project, like how it happened with a mongodb project.

**Comment by maoo** [comment]
Hi @AndreyKozlov1984 and @jordinl83 , thanks for your suggestions!

I've tried to use `open_source: true` on https://deploy-preview-135--finos-landscape.netlify.app/?license=not-open-source , but as you can see it doesn't seem to work, as the items are still listed as `Not Open Source`; this is the PR - https://github.com/finos/finos-landscape/pull/135/files 

Regarding the list of explicit licenses, yes, we would need basically 2 custom licenses, for now:
1. Something called `FINOS IP Policy`, that can link to https://www.finos.org/hubfs/FINOS/governance/FINOS%20IP%20Policy.pdf
2. `CSLA 1.0`, which you can find on https://spdx.org/licenses/Community-Spec-1.0.html and https://github.com/CommunitySpecification/1.0

If those can be added with something like `license: CSLA 1.0`, that would solve all our problems.

Thanks!

**Comment by AndreyKozlov1984** [comment]
my plan is to allow to explicitly mention a license. There will not be any link to a license directly, you can use extra fields for that purpose.

The idea is just to add a `license: CSLA 1.0`  to the entry, and if you need an url for your end users - provide `extra: { license_url: http://....... } ` to display a license url as well

**Comment by maoo** [comment]
Perfect. Do you have any ETA for `license: CSLA 1.0` ?

**Comment by robmoffat** [comment]
@robmoffat and @maoo to run through and see what's left - add to this issue.

**Comment by maoo** [comment]
Everything looks correct on landscape.finos.org , so I'm going to close this issue.

**Comment by AndreyKozlov1984** [comment]
I am going to add a support for custom licenses today.

**Comment by maoo** [comment]
Thanks @AndreyKozlov1984 for the heads up! When Doo, could you please send me (also here) a configuration sample? Ty!
