### ISSUE TITLE
Card mode should properly render only FINOS Projects

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-landscape#32]
Currently the card mode shows a mix of projects and members.

Please fix [here](https://github.com/finos/finos-landscape/blob/master/settings.yml#L43-L52) to only display FINOS projects.

**Comment by dankohn** [comment]
@mindthegab I would strongly encourage you to have card mode display all cards by default. Then use the filtering functionality to display just FINOS projects, just members, etc. For example:

Just CNCF-hosted projects
https://landscape.cncf.io/format=card-mode&project=hosted

Just CNCF members
https://landscape.cncf.io/category=cncf-members&format=card-mode&grouping=category

Just cards from China
https://landscape.cncf.io/format=card-mode&grouping=headquarters&headquarters=china,hong-kong,taiwan

If that works for you, please close this issue.

**Comment by mindthegab** [comment]
Makes sense @dankohn and thanks for the input. I think that would be ultimate goal. 

But for this v1, we have a data (as opposed to viz) issue to be fixed still as the [card mode](https://landscape.finos.org/format=card-mode) is bucketing items in a bit of random way (again, the problem coming from our data I think).

Meaning for example there are projects listed under the members section and vice versa...

Thanks for your contributions, I really appreciate you keeping an eye on how we evolve our landscape :)
