### ISSUE TITLE
Include the name of the project in every logo

### ISSUE THREAD

**Issue by dankohn** [finos/finos-landscape#39]
I strongly recommend that you include the name of the project in every logo, which both creates a unique icon for every card, and makes the static image useful: https://landscape.finos.org/images/landscape.png

On all the Symphony items, you can now do so by going to https://autocrop.cncf.io, entering the project name such as `Fugue` as a label, and dragging the Symphony SVG on to the left side. Then download and use the resulting logo with a label below it. Note that this has worked well for https://landscape.openmainframeproject.org/.

**Comment by mindthegab** [comment]
Thanks @toshaellison has been working on logos so reassigning to her.

**Comment by maoo** [comment]
Done
