### ISSUE TITLE
Can we suppress non-contextually relavent (or nulls) fields like Crunchbase from detailed tile

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-landscape#43]
See this screenshot from the Kdb project (cc @finos/dt-kdb, @alvin-c-shih ) 
![kdb-project-tiles](https://user-images.githubusercontent.com/2136904/87332077-09527d80-c509-11ea-8c83-30f88db60df4.jpg)

- Crunchbase URLs: I don't anticipate the Kdb project, or probably any FINOS project, will have a Crunchbase page/profile anytime soon. For this project, the Crunchbase URL is the crunchbase url for FINOS, but the way the page is rendered it appears (to me at least) it looks like it should read as the crunchbase url for the Kdb project. Suggestions:
    - the crunchbase URL be nullable and if it's nulled the field not appear at all, or
    - the tile be laid out in such a way that it's more clear that this crunchbase URL is associated with the underlying foundation, not the project 

- LinkedIn URL: Same feedback as Crunchbase URL.

- Headquarters: This is about FINOS, right? Not Kdb? Kdb doesn't have a "headquarters". Can we suppress this?

- Latest Tweet/Twitter: Only a few FINOS projects have dedicated twitter handles; Kdb is an example of a project that does not have a Twitter handle. Looks like we're using the finosfoundation handle instead, so "latest tweet" is the latest finosfoundation tweet. But the way the page is laid out it appears the "latest tweet" is indicative of the latest tweet from the Kdb project, which is non-sensical. 

Overall it feels like the tile, in the way it's laid out, could confuse a viewer about which fields are properties of the open source project (e.g., kdb) vs. the underlying foundation (e.g., FINOS). I'd recommend revising the layout to better distinguish fields about the project vs. field about the underlying foundation.

**Comment by maoo** [comment]
We'd also like to remove the `No CII Best Practices`, since FINOS doesn't enforce CII for our hosted projects.

**Comment by brooklynrob** [comment]
@maoo @dankohn As I have shared with Mao, we really need to remove the "No CII Best Practices" ASAP -- we now have all of the FINOS projects showing a badge says we have "No (CII) Best Practices" and it's just an unforced public relations, perception setting error when people are checking out our project -- just raises questions and creates FUD. How can we do that?

**Comment by dankohn** [comment]
You should be set now: https://github.com/finos/finos-landscape/commit/f1ccb3d34a668e9ddfaca2d3b91dda2b065cfdce

**Comment by maoo** [comment]
TY @dankohn and @AndreyKozlov1984 !

**Comment by maoo** [comment]
I think we managed to remove all non-relevant info! If there's anything left to remove, we could add separate improvement issues.
