### ISSUE TITLE
Why the tweet number is 0 ?

### ISSUE THREAD

**Issue by maoo** [finos/finos-landscape#46]
<img width="281" alt="Screenshot 2020-07-20 at 16 55 31" src="https://user-images.githubusercontent.com/327285/87952207-d7fa2480-caa9-11ea-8117-4461a01ef9ce.png">

Not sure what the tweet number refers to, I believe it looks for all tweets that contain the term `landscape.finos.org`. If that's the case, we may want to run some activity on twitter to share the link across our members and community.

/CC @toshaellison

**Comment by dankohn** [comment]
Exactly.

**Comment by mindthegab** [comment]
Yes @maoo, @toshaellison  decided to  not announce the landscape broadly yet. 

We're gonna do a little more tide up this week (e.g. #47 , #43, #40, etc.) and that this # should go up. I've raised https://github.com/finos/finos-landscape/issues/48 to track the announce work and assigned to @toshaellison. You can keep this issue open and we'll check if it works once we make some noise 😉 

BTW, thanks @dankohn for all your help so far. Now that we are on the other side of the GB meeting, we should be able to do some more work on this.

**Comment by maoo** [comment]
No more 0! closing issue.

**Comment by AndreyKozlov1984** [comment]
Great!
