### ISSUE TITLE
Integrate FINOS lifecycle stage

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-landscape#47]
This means:
- [x] Update FINOS metadata -> landscape.yml generation to include lifecycle stage.
- [x] Filter by lifecycle stage (formation, incubating, active, archived) both in landscape and card mode
- [x] Each project is color coded and shows lifecycle stage in the landscape overall view (e.g. like in l.cncf.io)
- [x] [FINOS badges](https://landscape.cncf.io/) displayed in the landscape detail view (popup when you click on a project)
- [x] [FINOS badges](https://landscape.cncf.io/) displayed in the card mode both overall and detail view (popup when you click on a project)

**Comment by maoo** [comment]
@toshaellison @mindthegab - please review https://deploy-preview-56--finos-landscape.netlify.app/ and let me know if you're ok for me to merge. TY

**Comment by dankohn** [comment]
I strongly recommend adding text below each logo Symphony project before merging. One of the ideas of the landscape is that it is supposed to be useful without needing to click on a project first.

The first logo would say "Fugue" underneath and the second would say "Integration Bridge". We allow you to automatically add text below an SVG using https://autocrop.cncf.io/. That's how I add country and project name below each flag at https://landscape.lfph.io/.

Separately, I would also strongly encourage you to add your members to the landscape view, as we do with https://landscape.lfph.io/.

**Comment by dankohn** [comment]
Great. Please ask if you have any questions about adding the labels.

**Comment by maoo** [comment]
PR is merged, closing issue. Thanks a lot @dankohn and @AndreyKozlov1984 for your help!
