### ISSUE TITLE
Add FINOS Members to the landscape 

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-landscape#61]
For the v2 we can consider adding Members to:

- [ ] Landscape view
- [ ] Card mode
- [ ] Optionally single source finos.org/members from the same framework

I think it would be important to make sure that:

1. we have consolidated our metadata with the LF backend/crm infrastructure to single source membership information
2. we have decided our website strategy on the LF infra (i.e. will https://www.finos.org/members be sourced from the landscape)

**Comment by jmertic** [comment]
I made a PR that does this in an automated way - let me know your thoughts...

#88

**Comment by maoo** [comment]
Let's keep working on https://github.com/finos/finos-landscape/pull/88 , we're almost there, we just need to refine a bit the layout. TY @jmertic !
