### ISSUE TITLE
Symphony project logos

### ISSUE THREAD

**Issue by maoo** [finos/finos-landscape#86]
- [x] Build logos for each Symphony project not led by Symphony
  - [x] Symphony Java Toolkit
  - Unfurl Bot (?)
  - Symphony Clojure client (?)
  - Symphony Hubot client (?)
- [x] Build basic logo for generic Symphony logos
  - [x] All other projects listed in https://landscape.finos.org/card-mode?category=symphony-ecosystem&grouping=category

**Comment by toshaellison** [comment]
@maoo Can you replace the existing Symphony logo for the Symphony Java Toolkit with this one https://github.com/finos/branding/blob/master/project-logos/active-project-logos/Symphony%20Java%20Toolkit%20Logo/Vertical/2020_SJT_Logo_Vertical.svg

**Comment by maoo** [comment]
> @maoo Can you replace the existing Symphony logo for the Symphony Java Toolkit with this one https://github.com/finos/branding/blob/master/project-logos/active-project-logos/Symphony%20Java%20Toolkit%20Logo/Vertical/2020_SJT_Logo_Vertical.svg

Done! See https://landscape.finos.org/

**Comment by toshaellison** [comment]
Thank you!!

**Comment by maoo** [comment]
Landscape updated - https://landscape.finos.org/

4 logos are still missing tho.

**Comment by toshaellison** [comment]
Thanks Mao. We normally use the vertical lockup version of the logos.Since those remaining 4 are not led by Symphony the process is different. If you confirm that they will not potentially be archived then I can get those done too.

**Comment by maoo** [comment]
Good point on archivable projects! I think that https://github.com/symphonyoss/canon is the only project that would be worth adding, the other three IMO should be proposed for archival.

Do you think we can close this issue and create 2 new ones:
1. Get Canon logo
2. Archive proposal for `Symphony Clojure Client`, `Symphony Hubot Client` and `Unfurl Bot`

WDYT?

**Comment by toshaellison** [comment]
Yes!

**Comment by maoo** [comment]
Canon logo done. Closing issue.
