### ISSUE TITLE
Innersource project description is not pulled from GitHub

### ISSUE THREAD

**Issue by maoo** [finos/finos-landscape#93]
In https://landscape.finos.org/?selected=inner-source-special-interest-group the description is not taken from the **About** section on https://github.com/finos/InnerSource (as expected).

We already deployed 2 changes, but the description is not pulled; is there any way to force loading project descriptions?

/CC @jordinl83 @mcleo-d

**Comment by jordinl83** [comment]
@maoo I think it shows the right description now. Could you check?

**Comment by maoo** [comment]
> @maoo I think it shows the right description now. Could you check?

Yes, thank you @jordinl83  ! Out of curiosity, how often are descriptions pulled?

**Comment by jordinl83** [comment]
@maoo Repo and crunchbase data are pulled the first time an item is added to the landscape. After that the data is refreshed daily. I think you might have updated the repo description but the daily job hadn't run yet.

**Comment by maoo** [comment]
> @maoo Repo and crunchbase data are pulled the first time an item is added to the landscape. After that the data is refreshed daily. I think you might have updated the repo description but the daily job hadn't run yet.

Gotcha... and I think that only applies to `master` content, which is what I think I didn't consider. TY!
